<div class="mt-6">
    <div class="flex justify-between items-center">
        <h3 class="flex items-center"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2724%27%20height=%2724%27/%3e"></span><img alt="" src="/_next/image?url=%2Fimg%2Foccupation-icon%2Ftitle.png&amp;w=48&amp;q=75" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" srcset="/_next/image?url=%2Fimg%2Foccupation-icon%2Ftitle.png&amp;w=32&amp;q=75 1x, /_next/image?url=%2Fimg%2Foccupation-icon%2Ftitle.png&amp;w=48&amp;q=75 2x"><noscript><img alt="" srcSet="/_next/image?url=%2Fimg%2Foccupation-icon%2Ftitle.png&amp;w=32&amp;q=75 1x, /_next/image?url=%2Fimg%2Foccupation-icon%2Ftitle.png&amp;w=48&amp;q=75 2x" src="/_next/image?url=%2Fimg%2Foccupation-icon%2Ftitle.png&amp;w=48&amp;q=75" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" loading="lazy" /></noscript></span><span class="ml-1 font-bold text-16 text-se-neutral-100-n">Nghề nghiệp nổi bật</span></h3><button type="button" class="text-se-accent-100 text-14 font-semibold">Xem tất cả</button>
    </div>
    <div class="grid grid-cols-3 lg:grid-cols-7 gap-x-1 gap-y-2 lg:gap-3 mt-6">
        <div class="w-full text-center flex"><a class="w-full outline-none block border transition-all duration-75 border-transparent hover:border-se-accent-100 rounded-lg p-2 lg:p-[14px] hover:shadow-lg" href="/mien-nam/viec-lam-ban-si-ban-le-quan-ly-cua-hang-o6.html"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2756%27%20height=%2756%27/%3e"></span><img alt="" src="/_next/image?url=%2Fimg%2Foccupation-icon%2F6.png&amp;w=128&amp;q=75" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" srcset="/_next/image?url=%2Fimg%2Foccupation-icon%2F6.png&amp;w=64&amp;q=75 1x, /_next/image?url=%2Fimg%2Foccupation-icon%2F6.png&amp;w=128&amp;q=75 2x"></span>
                <div class="flex items-center justify-center"><span class="font-bold text-se-accent-100 text-12 lg:text-16">1,100</span><span class="text-grey-11 text-12 font-medium ml-1">việc</span></div>
                <div class="line-clamp-2 font-semibold text-12 lg:text-14 text-se-neutral-84 leading-4">Bán sỉ - Bán lẻ - Quản lý cửa hàng</div>
            </a></div>
        <div class="w-full text-center flex"><a class="w-full outline-none block border transition-all duration-75 border-transparent hover:border-se-accent-100 rounded-lg p-2 lg:p-[14px] hover:shadow-lg" href="/mien-nam/viec-lam-ban-hang-kinh-doanh-o13.html"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2756%27%20height=%2756%27/%3e"></span><img alt="" src="/_next/image?url=%2Fimg%2Foccupation-icon%2F13.png&amp;w=128&amp;q=75" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" srcset="/_next/image?url=%2Fimg%2Foccupation-icon%2F13.png&amp;w=64&amp;q=75 1x, /_next/image?url=%2Fimg%2Foccupation-icon%2F13.png&amp;w=128&amp;q=75 2x"></span>
                <div class="flex items-center justify-center"><span class="font-bold text-se-accent-100 text-12 lg:text-16">2,400</span><span class="text-grey-11 text-12 font-medium ml-1">việc</span></div>
                <div class="line-clamp-2 font-semibold text-12 lg:text-14 text-se-neutral-84 leading-4">Bán hàng - Kinh doanh</div>
            </a></div>
        <div class="w-full text-center flex"><a class="w-full outline-none block border transition-all duration-75 border-transparent hover:border-se-accent-100 rounded-lg p-2 lg:p-[14px] hover:shadow-lg" href="/mien-nam/viec-lam-marketing-o12.html"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2756%27%20height=%2756%27/%3e"></span><img alt="" src="/_next/image?url=%2Fimg%2Foccupation-icon%2F12.png&amp;w=128&amp;q=75" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" srcset="/_next/image?url=%2Fimg%2Foccupation-icon%2F12.png&amp;w=64&amp;q=75 1x, /_next/image?url=%2Fimg%2Foccupation-icon%2F12.png&amp;w=128&amp;q=75 2x"></span>
                <div class="flex items-center justify-center"><span class="font-bold text-se-accent-100 text-12 lg:text-16">750</span><span class="text-grey-11 text-12 font-medium ml-1">việc</span></div>
                <div class="line-clamp-2 font-semibold text-12 lg:text-14 text-se-neutral-84 leading-4">Marketing</div>
            </a></div>
        <div class="w-full text-center flex"><a class="w-full outline-none block border transition-all duration-75 border-transparent hover:border-se-accent-100 rounded-lg p-2 lg:p-[14px] hover:shadow-lg" href="/mien-nam/viec-lam-khoa-hoc-ky-thuat-o34.html"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2756%27%20height=%2756%27/%3e"></span><img alt="" src="/_next/image?url=%2Fimg%2Foccupation-icon%2F34.png&amp;w=128&amp;q=75" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" srcset="/_next/image?url=%2Fimg%2Foccupation-icon%2F34.png&amp;w=64&amp;q=75 1x, /_next/image?url=%2Fimg%2Foccupation-icon%2F34.png&amp;w=128&amp;q=75 2x"></span>
                <div class="flex items-center justify-center"><span class="font-bold text-se-accent-100 text-12 lg:text-16">750</span><span class="text-grey-11 text-12 font-medium ml-1">việc</span></div>
                <div class="line-clamp-2 font-semibold text-12 lg:text-14 text-se-neutral-84 leading-4">Khoa học - Kỹ thuật</div>
            </a></div>
        <div class="w-full text-center flex"><a class="w-full outline-none block border transition-all duration-75 border-transparent hover:border-se-accent-100 rounded-lg p-2 lg:p-[14px] hover:shadow-lg" href="/mien-nam/viec-lam-nghe-nghiep-khac-o35.html"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2756%27%20height=%2756%27/%3e"></span><img alt="" src="/_next/image?url=%2Fimg%2Foccupation-icon%2F35.png&amp;w=128&amp;q=75" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" srcset="/_next/image?url=%2Fimg%2Foccupation-icon%2F35.png&amp;w=64&amp;q=75 1x, /_next/image?url=%2Fimg%2Foccupation-icon%2F35.png&amp;w=128&amp;q=75 2x"></span>
                <div class="flex items-center justify-center"><span class="font-bold text-se-accent-100 text-12 lg:text-16">400</span><span class="text-grey-11 text-12 font-medium ml-1">việc</span></div>
                <div class="line-clamp-2 font-semibold text-12 lg:text-14 text-se-neutral-84 leading-4">Nghề nghiệp khác</div>
            </a></div>
        <div class="w-full text-center flex"><a class="w-full outline-none block border transition-all duration-75 border-transparent hover:border-se-accent-100 rounded-lg p-2 lg:p-[14px] hover:shadow-lg" href="/mien-nam/viec-lam-hanh-chinh-thu-ky-o1.html"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2756%27%20height=%2756%27/%3e"></span><img alt="" src="/_next/image?url=%2Fimg%2Foccupation-icon%2F1.png&amp;w=128&amp;q=75" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" srcset="/_next/image?url=%2Fimg%2Foccupation-icon%2F1.png&amp;w=64&amp;q=75 1x, /_next/image?url=%2Fimg%2Foccupation-icon%2F1.png&amp;w=128&amp;q=75 2x"></span>
                <div class="flex items-center justify-center"><span class="font-bold text-se-accent-100 text-12 lg:text-16">900</span><span class="text-grey-11 text-12 font-medium ml-1">việc</span></div>
                <div class="line-clamp-2 font-semibold text-12 lg:text-14 text-se-neutral-84 leading-4">Hành chính - Thư ký</div>
            </a></div>
        <div class="w-full text-center flex"><a class="w-full outline-none block border transition-all duration-75 border-transparent hover:border-se-accent-100 rounded-lg p-2 lg:p-[14px] hover:shadow-lg" href="/mien-nam/viec-lam-ke-toan-o17.html"><span style="box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%"><img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2756%27%20height=%2756%27/%3e"></span><img alt="" src="/_next/image?url=%2Fimg%2Foccupation-icon%2F17.png&amp;w=128&amp;q=75" decoding="async" data-nimg="intrinsic" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" srcset="/_next/image?url=%2Fimg%2Foccupation-icon%2F17.png&amp;w=64&amp;q=75 1x, /_next/image?url=%2Fimg%2Foccupation-icon%2F17.png&amp;w=128&amp;q=75 2x"></span>
                <div class="flex items-center justify-center"><span class="font-bold text-se-accent-100 text-12 lg:text-16">950</span><span class="text-grey-11 text-12 font-medium ml-1">việc</span></div>
                <div class="line-clamp-2 font-semibold text-12 lg:text-14 text-se-neutral-84 leading-4">Kế toán</div>
            </a></div>
    </div>
</div>