<section id="blog-section" class="jsx-cac5aaefe2a56ab wp-container-fluid relative flex flex-col w-full lg:mb-16 mb-10">
    <p class="jsx-cac5aaefe2a56ab font-bold lg:text-[32px] text-2xl text-center w-full leading-[48px] mb-0 md:mb-4 mt-0 md:mt-9 select-none">Cẩm nang nghề nghiệp</p>
    <div class="jsx-cac5aaefe2a56ab relative lg:h-[380px] h-full justify-self-center lg:w-11/12 w-11/12 m-auto gap-x-10 lg:justify-items-center md:grid md:grid-cols-3">
        <div data-track-content="true" data-content-name="vl24h.enews.trangchu" data-content-piece="Top 10 việc làm online cho sinh viên uy tín giúp bạn bỏ túi thu nhập khủng" data-content-target="/?utm_source=vieclam24h.vn&amp;utm_medium=referral&amp;utm_campaign=site-vieclam24h.vn&amp;utm_content=home-page" class="jsx-cac5aaefe2a56ab relative flex flex-col overflow-hidden w-full lg:h-full m-auto lg:mb-0 mb-4 box-border p-3 hover:shadow-lg rounded"><a href="https://nghenghiep.vieclam24h.vn/la-ban-su-nghiep/viec-lam-online-cho-sinh-vien/?utm_source=vieclam24h.vn&amp;utm_medium=referral&amp;utm_campaign=site-vieclam24h.vn&amp;utm_content=home-page" target="_blank" rel="noreferrer" class="jsx-cac5aaefe2a56ab"><img class="relative rounded object-cover h-[195px] w-full select-none" src="https://nghenghiep.vieclam24h.vn/wp-content/uploads/2023/11/viec-lam-online-cho-sinh-vien.webp" alt="blog_avt">
                <p class="jsx-cac5aaefe2a56ab line-clamp-1 overflow-hidden overflow-ellipsis relative mt-5 mb-3 text-18 leading-8 font-semibold">Top 10 việc làm online cho sinh viên uy tín giúp bạn bỏ túi thu nhập khủng</p>
                <div class="jsx-cac5aaefe2a56ab line-clamp-3 overflow-hidden overflow-ellipsis relative text-14">
                    <p>Ngày nay, với sự phát triển vượt bậc của công nghệ đã mở ra nhiều cơ hội việc làm online hấp dẫn dành cho các bạn sinh viên. Một số công việc online cho sinh viên uy tín không chỉ mang lại thu nhập mà còn là cơ hội để các bạn phát triển bản […]</p>
                </div>
            </a></div>
        <div data-track-content="true" data-content-name="vl24h.enews.trangchu" data-content-piece="Lưu lại ngay cách gửi CV qua email tạo ấn tượng tốt với nhà tuyển dụng" data-content-target="/?utm_source=vieclam24h.vn&amp;utm_medium=referral&amp;utm_campaign=site-vieclam24h.vn&amp;utm_content=home-page" class="jsx-cac5aaefe2a56ab relative flex flex-col overflow-hidden w-full lg:h-full m-auto lg:mb-0 mb-4 box-border p-3 hover:shadow-lg rounded"><a href="https://nghenghiep.vieclam24h.vn/la-ban-su-nghiep/cach-gui-cv-qua-email/?utm_source=vieclam24h.vn&amp;utm_medium=referral&amp;utm_campaign=site-vieclam24h.vn&amp;utm_content=home-page" target="_blank" rel="noreferrer" class="jsx-cac5aaefe2a56ab"><img class="relative rounded object-cover h-[195px] w-full select-none" src="https://nghenghiep.vieclam24h.vn/wp-content/uploads/2023/11/cach-gui-cv-qua-email.webp" alt="blog_avt">
                <p class="jsx-cac5aaefe2a56ab line-clamp-1 overflow-hidden overflow-ellipsis relative mt-5 mb-3 text-18 leading-8 font-semibold">Lưu lại ngay cách gửi CV qua email tạo ấn tượng tốt với nhà tuyển dụng</p>
                <div class="jsx-cac5aaefe2a56ab line-clamp-3 overflow-hidden overflow-ellipsis relative text-14">
                    <p>Việc gửi CV qua email để ứng tuyển vào các vị trí làm việc không còn là điều xa lạ đối với đa số ứng viên. Tuy nhiên, không phải ai cũng biết cách gửi CV qua email hay cách gửi mail ứng tuyển thu hút và để lại ấn tượng tích cực với nhà […]</p>
                </div>
            </a></div>
        <div data-track-content="true" data-content-name="vl24h.enews.trangchu" data-content-piece="11 công việc cho người hướng nội lý tưởng nhất để bạn luôn tỏa sáng" data-content-target="/?utm_source=vieclam24h.vn&amp;utm_medium=referral&amp;utm_campaign=site-vieclam24h.vn&amp;utm_content=home-page" class="jsx-cac5aaefe2a56ab relative flex flex-col overflow-hidden w-full lg:h-full m-auto lg:mb-0 mb-4 box-border p-3 hover:shadow-lg rounded"><a href="https://nghenghiep.vieclam24h.vn/la-ban-su-nghiep/cong-viec-cho-nguoi-huong-noi/?utm_source=vieclam24h.vn&amp;utm_medium=referral&amp;utm_campaign=site-vieclam24h.vn&amp;utm_content=home-page" target="_blank" rel="noreferrer" class="jsx-cac5aaefe2a56ab"><img class="relative rounded object-cover h-[195px] w-full select-none" src="https://nghenghiep.vieclam24h.vn/wp-content/uploads/2023/11/cong-viec-cho-nguoi-huong-noi-1.webp" alt="blog_avt">
                <p class="jsx-cac5aaefe2a56ab line-clamp-1 overflow-hidden overflow-ellipsis relative mt-5 mb-3 text-18 leading-8 font-semibold">11 công việc cho người hướng nội lý tưởng nhất để bạn luôn tỏa sáng</p>
                <div class="jsx-cac5aaefe2a56ab line-clamp-3 overflow-hidden overflow-ellipsis relative text-14">
                    <p>Ngày nay, người hướng nội có thể gặp khó khăn khi phát triển trong một thế giới dường như coi trọng tính hướng ngoại nhiều hơn. Do đó nếu bạn là người hướng nội, bạn cần phải biết thế mạnh của mình ở đâu để tìm công việc phù hợp. Dưới đây là top 11 […]</p>
                </div>
            </a></div>
    </div><a href="https://nghenghiep.vieclam24h.vn/?utm_source=vieclam24h.vn&amp;utm_medium=referral&amp;utm_campaign=site-vieclam24h.vn&amp;utm_content=footer" target="_blank" rel="noreferrer" class="jsx-cac5aaefe2a56ab border-[1.5px] select-none leading-3 border-se-blue-10 hover:border-se-accent-100 hover:text-se-accent-100 rounded relative mx-auto lg:mt-6 mt-3 text-center px-5 py-3 font-semibold text-primary bg-[#F5F1FF] text-14">Xem thêm cẩm nang nghề nghiệp</a>
</section>