on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 103.167.199.37
        username: vieclam@vieclam24.com.vn
        password: E8c1BPGP
        server-dir: /public_html/wp-content/themes/vieclam24/
        dangerous-clean-slate: true
        timeout: 300
